### ISSUE TITLE
Touch screen keyboard issue with accented characters

### ISSUE THREAD

**Issue by kosszarva** [Salamek/chromium-kiosk#64]
Dear Salamek,
We have run into a bug when we tried to type with virtual keyboard.
The accented characters are not working well (for example "ő", "ű"), they are hidden behind the normal characters during typing.
Probably it is a sizing issue.
Thank you for your hard work and for this great package.
Have a nice day,
Levente

**Comment by Salamek** [comment]
Hi, what type of backend are you using? new [qiosk](https://github.com/Salamek/) or normal chromium?

**Comment by kosszarva** [comment]
hi,
i use qiosk, attached a video.
Thank you,
Levente

https://user-images.githubusercontent.com/86241571/186638391-7fae9606-d6ef-4d9d-857a-7671f2cbeba5.mp4

**Comment by Salamek** [comment]
@kosszarva ok, that video helps a lot, can i ask what OS are you using (Name/Version)?

**Comment by kosszarva** [comment]
Debian 11 tiny 64bit with updates.

**Comment by Salamek** [comment]
Ok, this is caused by "hack" that attempts to fix virtual keyboard on QT <=5.15.3 to not overlay whole screen when displayed...

So i have added a condition to qiosk to do not apply this hack when QT is 5.15.4>= and that fixes it when using newer QT, issue is that Debian stable (11) have only 5.15.3 in repository, so to get newer fixed version of QT you have to migrate your Debian installation to Debian testing: https://www.makeuseof.com/switch-from-debian-stable-to-testing/

**Comment by Salamek** [comment]
Hmm looks like it is broken on 5.15.4 too... hmm i think i will need to migrate to QT6... god..

**Comment by kosszarva** [comment]
Thank you! It's working now with the new package.
Have a great day!
